import React from "react";
import styled from "@emotion/styled";
/**
 * `<_2>` ('검사 진행 페이지 (2)')
 * - [Open in Figma](https://figma.com/file/NlD9D8mc0GTNdluwALGs8v?node-id=86:720)
 * - [Open in Grida](https://code.grida.co/files/NlD9D8mc0GTNdluwALGs8v?node=86:720)
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <_2/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/e743bc03-c0ef-4382-a2e0-7df19a5832e2)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://NlD9D8mc0GTNdluwALGs8v/86:720 -->
 */
export function ExaminationProgress() {
  return (
    <RootWrapper2>
      <Frame50>
        <IconsBasicUser
          src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/218a5939-c8dd-4449-a936-47efae3f66e6"
          alt="icon"
        />
        <NaN_0001>검사 진행</NaN_0001>
      </Frame50>
      <NaN_0002>검사 진행</NaN_0002>
      <Group32>
        <Rectangle42 />
        <Rectangle43 />
        <NaN_0003>오늘 경제생활에 얼마나 만족하는가?</NaN_0003>
        <Rectangle44 />
        <Rectangle44 />
        <Group28>
          <Rectangle29 />
          <NaN_0004>활발하고 내 의견을 얘기할 때 당당한 편!</NaN_0004>
        </Group28>
        <Group28>
          <Rectangle29 />
          <NaN_0004>
            오늘 경제생활에 대해 <br />
            만족하지 않는다.
          </NaN_0004>
        </Group28>
        <NaN_0006>어느정도 만족한다!</NaN_0006>
        <Group30>
          <IconsBasicArrowLeft
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/9c1cc81d-9e9f-4230-b7f3-4d26b3322562"
            alt="icon"
          />
          <IconsBasicArrowRight4
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/a5ff0eb4-fe9c-4c85-8064-6757b1198a04"
            alt="icon"
          />
          <_112>1/12</_112>
        </Group30>
        <Group30>
          <IconsBasicArrowLeft
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/344e67db-3666-4dbf-8339-2397511cf8be"
            alt="icon"
          />
          <IconsBasicArrowRight4
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/5364df77-1f94-4812-a3db-6d9e8277e5b0"
            alt="icon"
          />
          <_112>1/12</_112>
        </Group30>
      </Group32>
      <Frame51>
        <Frame1>
          <Group54>
            <IconsBasicProject
              src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/ce5c2076-be64-4001-9ca4-091dabb0406a"
              alt="icon"
            />
            <NaN_0007>나의 도형</NaN_0007>
          </Group54>
          <Group53>
            <IconsBasicChat
              src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/1a61b57a-5956-4a9a-a4ee-5302e0709038"
              alt="icon"
            />
            <NaN_0008>고민 나눔</NaN_0008>
          </Group53>
          <Group52>
            <IconlyRegularTwoToneHome>
              <Home>
                <Home_0001
                  src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/b95479c6-889b-4fbf-95bd-1ee576783070"
                  alt="image of Home"
                />
              </Home>
            </IconlyRegularTwoToneHome>
            <NaN_0009>홈</NaN_0009>
          </Group52>
          <Group51>
            <IconsBasicStar
              src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/5b7cff32-c237-4d30-bbce-b7bb86dc5830"
              alt="icon"
            />
            <NaN_0010>칭찬 일기</NaN_0010>
          </Group51>
          <Group50>
            <NaN_0011>집중 기록</NaN_0011>
            <IconsBasicTime
              src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/c71999c8-a859-41c7-b3f4-c2c714da1ff1"
              alt="icon"
            />
          </Group50>
        </Frame1>
      </Frame51>
      <Vector xmlns="http://www.w3.org/2000/svg">
        <path
          fill="rgba(0, 0, 0, 0.64)"
          d="M0 7.50001C0 7.74737 0.118471 7.97494 0.333872 8.16294L7.4852 14.723C7.7006 14.911 7.92677 15 8.18525 15C8.71299 15 9.13302 14.6439 9.13302 14.1491C9.13302 13.9117 9.03609 13.6742 8.86377 13.5257L6.45127 11.2698L2.18633 7.6979L1.96015 8.18273L5.42811 8.38062L19.0523 8.38062C19.6123 8.38062 20 8.01452 20 7.50001C20 6.9855 19.6123 6.6194 19.0523 6.6194L5.42811 6.6194L1.96015 6.81729L2.18633 7.31202L6.45127 3.73022L8.86377 1.47427C9.03609 1.31596 9.13302 1.08839 9.13302 0.850923C9.13302 0.356201 8.71299 0 8.18525 0C7.92677 0 7.7006 0.0791558 7.46365 0.296834L0.333872 6.83708C0.118471 7.02507 0 7.25265 0 7.50001Z"
        />
      </Vector>
    </RootWrapper2>
  );
}

const RootWrapper2 = styled.div`
  min-height: 100vh;
  background: rgb(255, 255, 255);
  background-repeat: no-repeat;
  background-size: contain;
  background-position: center;
  position: relative;
`;

const Frame50 = styled.div`
  width: 360px;
  height: 54px;
  overflow: hidden;
  background: rgb(245, 239, 231);
  background-repeat: no-repeat;
  background-size: contain;
  background-position: center;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const IconsBasicUser = styled.img`
  width: 19px;
  height: 18px;
  object-fit: cover;
  position: absolute;
  left: 323px;
  top: 19px;
`;

const NaN_0001 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 18px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  text-align: center;
  width: 80px;
  position: absolute;
  left: 143px;
  top: 16px;
`;

const NaN_0002 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 20px;
  font-family: Inter, sans-serif;
  font-weight: 600;
  text-align: center;
  width: 86px;
  min-height: 12px;
  position: absolute;
  left: 140px;
  top: 196px;
  height: 12px;
`;

const Group32 = styled.div`
  width: 401px;
  height: 349px;
  position: absolute;
  left: -21px;
  top: 250px;
`;

const Rectangle42 = styled.div`
  width: 401px;
  height: 312px;
  background: rgb(244, 244, 244);
  background-repeat: no-repeat;
  background-size: contain;
  background-position: center;
  border-radius: 20px;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const Rectangle43 = styled.div`
  width: 401px;
  height: 312px;
  background: rgb(244, 244, 244);
  background-repeat: no-repeat;
  background-size: contain;
  background-position: center;
  border: solid 0px black;
  border-radius: 20px;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const NaN_0003 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 18px;
  font-family: Poppins, sans-serif;
  font-weight: 500;
  text-align: center;
  width: 195px;
  min-height: 78px;
  position: absolute;
  left: 113px;
  top: 0px;
  height: 78px;
`;

const Rectangle44 = styled.div`
  width: 283px;
  height: 95px;
  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
  background: rgb(255, 255, 255);
  background-repeat: no-repeat;
  background-size: contain;
  background-position: center;
  border-radius: 20px;
  position: absolute;
  left: 65px;
  top: 72px;
  filter: blur(4px);
`;

const Group28 = styled.div`
  width: 283px;
  height: 95px;
  position: absolute;
  left: 63px;
  top: 190px;
`;

const Rectangle29 = styled.div`
  width: 283px;
  height: 95px;
  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
  background: rgb(245, 239, 231);
  background-repeat: no-repeat;
  background-size: contain;
  background-position: center;
  border-radius: 20px;
  position: absolute;
  left: 0px;
  top: 0px;
  filter: blur(4px);
`;

const NaN_0004 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 15px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  text-align: center;
  width: 248px;
  position: absolute;
  left: 29px;
  top: 34px;
`;

const NaN_0006 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 15px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  text-align: center;
  width: 237px;
  position: absolute;
  left: 92px;
  top: 113px;
`;

const Group30 = styled.div`
  width: 107px;
  height: 23px;
  position: absolute;
  left: 151px;
  top: 326px;
`;

const IconsBasicArrowLeft = styled.img`
  width: 20px;
  height: 20px;
  object-fit: cover;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const IconsBasicArrowRight4 = styled.img`
  width: 20px;
  height: 20px;
  object-fit: cover;
  position: absolute;
  left: 87px;
  top: 0px;
`;

const _112 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 18px;
  font-family: Poppins, sans-serif;
  font-weight: 500;
  text-align: center;
  width: 43px;
  min-height: 23px;
  position: absolute;
  left: 32px;
  top: 0px;
  height: 23px;
`;

const Frame51 = styled.div`
  width: 360px;
  height: 52px;
  overflow: hidden;
  background: rgb(245, 239, 231);
  background-repeat: no-repeat;
  background-size: contain;
  background-position: center;
  position: absolute;
  left: 0px;
  top: 748px;
`;

const Frame1 = styled.div`
  width: 360px;
  height: 52px;
  overflow: hidden;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const Group54 = styled.div`
  width: 41px;
  height: 30px;
  position: absolute;
  left: 297px;
  top: 16px;
`;

const IconsBasicProject = styled.img`
  object-fit: cover;
  position: absolute;
  left: 10px;
  top: 0px;
  right: 10px;
  bottom: 11px;
`;

const NaN_0007 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 8px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  text-align: center;
  width: 47px;
  position: absolute;
  left: 0px;
  top: 20px;
`;

const Group53 = styled.div`
  width: 36px;
  height: 32px;
  position: absolute;
  left: 233px;
  top: 14px;
`;

const IconsBasicChat = styled.img`
  width: 20px;
  height: 20px;
  object-fit: cover;
  position: absolute;
  left: 8px;
  top: 0px;
`;

const NaN_0008 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 8px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  text-align: center;
  width: 42px;
  position: absolute;
  left: 0px;
  top: 22px;
`;

const Group52 = styled.div`
  width: 20px;
  height: 28px;
  position: absolute;
  left: 170px;
  top: 18px;
`;

const IconlyRegularTwoToneHome = styled.div`
  position: absolute;
  left: 0px;
  top: 0px;
  right: 0px;
  bottom: 11px;
`;

const Home = styled.div`
  width: 16px;
  height: 14px;
  position: absolute;
  left: 2px;
  top: 1px;
`;

const Home_0001 = styled.img`
  object-fit: cover;
  position: absolute;
  left: 0px;
  top: 0px;
  right: 0px;
  bottom: 0px;
`;

const NaN_0009 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 8px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  text-align: center;
  width: 14px;
  position: absolute;
  left: 3px;
  top: 18px;
`;

const Group51 = styled.div`
  width: 36px;
  height: 30px;
  position: absolute;
  left: 92px;
  top: 16px;
`;

const IconsBasicStar = styled.img`
  width: 20px;
  height: 20px;
  object-fit: cover;
  position: absolute;
  left: 8px;
  top: 0px;
`;

const NaN_0010 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 8px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  text-align: center;
  width: 42px;
  position: absolute;
  left: 0px;
  top: 20px;
`;

const Group50 = styled.div`
  width: 37px;
  height: 30px;
  position: absolute;
  left: 21px;
  top: 16px;
`;

const NaN_0011 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 8px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  text-align: center;
  width: 43px;
  position: absolute;
  left: 0px;
  top: 20px;
`;

const IconsBasicTime = styled.img`
  width: 20px;
  height: 20px;
  object-fit: cover;
  position: absolute;
  left: 9px;
  top: 0px;
`;

const Vector = styled.svg`
  width: 20px;
  height: 15px;
  position: absolute;
  left: 16px;
  top: 22px;
  right: 324px;
  bottom: 763px;
`;
