import React from "react";
import styled from "@emotion/styled";
/**
 * `<NaN>` ('검사 결과 페이지')
 * - [Open in Figma](https://figma.com/file/NlD9D8mc0GTNdluwALGs8v?node-id=78:510)
 * - [Open in Grida](https://code.grida.co/files/NlD9D8mc0GTNdluwALGs8v?node=78:510)
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <NaN/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/e0fff2c3-5e69-4088-9ba0-4350fff74bf8)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://NlD9D8mc0GTNdluwALGs8v/78:510 -->
 */
export function InspectionResults() {
  return (
    <RootWrapperNaN>
      <Frame51>
        <IconsBasicUser
          src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/1fdb39ff-c909-4ca3-ab44-6bd738d9b80b"
          alt="icon"
        />
        <Vector xmlns="http://www.w3.org/2000/svg">
          <path
            fill="rgba(0, 0, 0, 0.64)"
            d="M0 7.50001C0 7.74737 0.118471 7.97494 0.333872 8.16294L7.4852 14.723C7.7006 14.911 7.92677 15 8.18525 15C8.71299 15 9.13302 14.6439 9.13302 14.1491C9.13302 13.9117 9.03609 13.6742 8.86377 13.5257L6.45127 11.2698L2.18633 7.6979L1.96015 8.18273L5.42811 8.38062L19.0523 8.38062C19.6123 8.38062 20 8.01452 20 7.50001C20 6.9855 19.6123 6.6194 19.0523 6.6194L5.42811 6.6194L1.96015 6.81729L2.18633 7.31202L6.45127 3.73022L8.86377 1.47427C9.03609 1.31596 9.13302 1.08839 9.13302 0.850923C9.13302 0.356201 8.71299 0 8.18525 0C7.92677 0 7.7006 0.0791558 7.46365 0.296834L0.333872 6.83708C0.118471 7.02507 0 7.25265 0 7.50001Z"
          />
        </Vector>
      </Frame51>
      <NaN_0002>검사 결과</NaN_0002>
      <Group35>
        <Rectangle38 />
        <NaN_0003>건강</NaN_0003>
        <NaN_0004>여가</NaN_0004>
        <NaN_0005>학업</NaN_0005>
        <NaN_0006>인간관계</NaN_0006>
        <NaN_0007>경제</NaN_0007>
        <Star25 xmlns="http://www.w3.org/2000/svg">
          <path
            fill="rgb(217, 217, 217)"
            d="M95 0L140.23 32.7461L185.35 65.6434L168.184 118.779L150.84 171.857L95 171.95L39.1604 171.857L21.8162 118.779L4.64963 65.6434L49.7699 32.7461L95 0Z"
          />
        </Star25>
      </Group35>
      <Line13 />
      <NaN_0008>
        비록 결과가 완벽한 도형의 모습은 아니더라도, 우린 나다울 때 가장
        행복하다.
      </NaN_0008>
      <Group58>
        <_00>
          00님은 오늘 하루 건강, 여가, 학업에 만족하셨으며
          <br />
          내일 인간관계에 노력하실 것을 추천드립니다.
        </_00>
        <NaN_0009>결과 해석</NaN_0009>
      </Group58>
      <NaN_0010>* 각 지수는 상대적인 수치입니다.</NaN_0010>
      <Frame50>
        <Frame1>
          <Group54>
            <IconsBasicProject
              src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/0e0a3235-bbad-4311-bdcd-c6eb5f4cac2b"
              alt="icon"
            />
            <NaN_0011>나의 도형</NaN_0011>
          </Group54>
          <Group53>
            <IconsBasicChat
              src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/beb74ce1-3934-4f6d-9cc2-53969ffce53d"
              alt="icon"
            />
            <NaN_0012>고민 나눔</NaN_0012>
          </Group53>
          <Group52>
            <IconlyRegularTwoToneHome>
              <Home>
                <Home_0001
                  src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/6f8265f4-4a4c-4215-bba5-7c8bfbbe0b48"
                  alt="image of Home"
                />
              </Home>
            </IconlyRegularTwoToneHome>
            <NaN_0013>홈</NaN_0013>
          </Group52>
          <Group51>
            <IconsBasicStar
              src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/6e71e975-09ef-4916-a707-7636ed650140"
              alt="icon"
            />
            <NaN_0014>칭찬 일기</NaN_0014>
          </Group51>
          <Group50>
            <NaN_0015>집중 기록</NaN_0015>
            <IconsBasicTime
              src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/651ed9e7-568b-4f58-bb4f-4ab41bd9a3f3"
              alt="icon"
            />
          </Group50>
        </Frame1>
      </Frame50>
    </RootWrapperNaN>
  );
}

const RootWrapperNaN = styled.div`
  min-height: 100vh;
  background: rgb(255, 255, 255);
  background-repeat: no-repeat;
  background-size: contain;
  background-position: center;
  position: relative;
`;

const Frame51 = styled.div`
  width: 360px;
  height: 54px;
  overflow: hidden;
  background: rgb(245, 239, 231);
  background-repeat: no-repeat;
  background-size: contain;
  background-position: center;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const IconsBasicUser = styled.img`
  width: 19px;
  height: 18px;
  object-fit: cover;
  position: absolute;
  left: 323px;
  top: 19px;
`;

const Vector = styled.svg`
  width: 20px;
  height: 15px;
  position: absolute;
  left: 16px;
  top: 22px;
  right: 324px;
  bottom: 17px;
`;

const NaN_0002 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 20px;
  font-family: Inter, sans-serif;
  font-weight: 600;
  text-align: center;
  width: 103px;
  position: absolute;
  left: 130px;
  top: 100px;
`;

const Group35 = styled.div`
  width: 401px;
  height: 312px;
  position: absolute;
  left: -21px;
  top: 139px;
`;

const Rectangle38 = styled.div`
  width: 401px;
  height: 312px;
  background: rgb(244, 244, 244);
  background-repeat: no-repeat;
  background-size: contain;
  background-position: center;
  border: solid 0px black;
  border-radius: 20px;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const NaN_0003 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 15px;
  font-family: Inter, sans-serif;
  font-weight: 600;
  text-align: center;
  text-decoration: underline;
  width: 41px;
  position: absolute;
  left: 179px;
  top: 31px;
`;

const NaN_0004 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 15px;
  font-family: Inter, sans-serif;
  font-weight: 600;
  text-align: center;
  text-decoration: underline;
  width: 41px;
  position: absolute;
  left: 57px;
  top: 116px;
`;

const NaN_0005 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 15px;
  font-family: Inter, sans-serif;
  font-weight: 600;
  text-align: center;
  text-decoration: underline;
  width: 41px;
  position: absolute;
  left: 91px;
  top: 245px;
`;

const NaN_0006 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 15px;
  font-family: Inter, sans-serif;
  font-weight: 600;
  text-align: center;
  text-decoration: underline;
  width: 76px;
  position: absolute;
  left: 266px;
  top: 245px;
`;

const NaN_0007 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 15px;
  font-family: Inter, sans-serif;
  font-weight: 600;
  text-align: center;
  text-decoration: underline;
  width: 41px;
  position: absolute;
  left: 304px;
  top: 116px;
`;

const Star25 = styled.svg`
  width: 190px;
  height: 190px;
  position: absolute;
  left: 106px;
  top: 61px;
  right: 105px;
  bottom: 61px;
`;

const Line13 = styled.div`
  width: 360px;
  height: 0px;
  border-top: dashed 1px rgb(185, 185, 185);
  position: absolute;
  left: -1px;
  top: 589px;
`;

const NaN_0008 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 18px;
  font-family: Inter, sans-serif;
  font-weight: 100;
  text-align: center;
  width: 230px;
  position: absolute;
  left: 71px;
  top: 626px;
`;

const Group58 = styled.div`
  width: 360px;
  height: 78px;
  position: absolute;
  left: 0px;
  top: 481px;
`;

const _00 = styled.span`
  color: rgb(51, 51, 51);
  text-overflow: ellipsis;
  font-size: 13px;
  font-family: Poppins, sans-serif;
  font-weight: 500;
  text-align: center;
  text-decoration: underline;
  width: 360px;
  position: absolute;
  left: 0px;
  top: 38px;
`;

const NaN_0009 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 20px;
  font-family: Inter, sans-serif;
  font-weight: 600;
  text-align: center;
  width: 97px;
  min-height: 18px;
  position: absolute;
  left: 133px;
  top: 0px;
  height: 18px;
`;

const NaN_0010 = styled.span`
  color: rgb(51, 51, 51);
  text-overflow: ellipsis;
  font-size: 10px;
  font-family: Poppins, sans-serif;
  font-weight: 500;
  text-align: left;
  position: absolute;
  left: 6px;
  top: 431px;
`;

const Frame50 = styled.div`
  width: 360px;
  height: 52px;
  overflow: hidden;
  background: rgb(245, 239, 231);
  background-repeat: no-repeat;
  background-size: contain;
  background-position: center;
  position: absolute;
  left: 0px;
  top: 748px;
`;

const Frame1 = styled.div`
  width: 360px;
  height: 52px;
  overflow: hidden;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const Group54 = styled.div`
  width: 41px;
  height: 30px;
  position: absolute;
  left: 297px;
  top: 16px;
`;

const IconsBasicProject = styled.img`
  object-fit: cover;
  position: absolute;
  left: 10px;
  top: 0px;
  right: 10px;
  bottom: 11px;
`;

const NaN_0011 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 8px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  text-align: center;
  width: 44px;
  position: absolute;
  left: 0px;
  top: 20px;
`;

const Group53 = styled.div`
  width: 36px;
  height: 32px;
  position: absolute;
  left: 233px;
  top: 14px;
`;

const IconsBasicChat = styled.img`
  width: 20px;
  height: 20px;
  object-fit: cover;
  position: absolute;
  left: 8px;
  top: 0px;
`;

const NaN_0012 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 8px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  text-align: center;
  width: 39px;
  position: absolute;
  left: 0px;
  top: 22px;
`;

const Group52 = styled.div`
  width: 20px;
  height: 28px;
  position: absolute;
  left: 170px;
  top: 18px;
`;

const IconlyRegularTwoToneHome = styled.div`
  position: absolute;
  left: 0px;
  top: 0px;
  right: 0px;
  bottom: 11px;
`;

const Home = styled.div`
  width: 16px;
  height: 14px;
  position: absolute;
  left: 2px;
  top: 1px;
`;

const Home_0001 = styled.img`
  object-fit: cover;
  position: absolute;
  left: 0px;
  top: 0px;
  right: 0px;
  bottom: 0px;
`;

const NaN_0013 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 8px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  text-align: center;
  width: 14px;
  position: absolute;
  left: 3px;
  top: 18px;
`;

const Group51 = styled.div`
  width: 36px;
  height: 30px;
  position: absolute;
  left: 92px;
  top: 16px;
`;

const IconsBasicStar = styled.img`
  width: 20px;
  height: 20px;
  object-fit: cover;
  position: absolute;
  left: 8px;
  top: 0px;
`;

const NaN_0014 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 8px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  text-align: center;
  width: 39px;
  position: absolute;
  left: 0px;
  top: 20px;
`;

const Group50 = styled.div`
  width: 37px;
  height: 30px;
  position: absolute;
  left: 21px;
  top: 16px;
`;

const NaN_0015 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 8px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  text-align: center;
  width: 40px;
  position: absolute;
  left: 0px;
  top: 20px;
`;

const IconsBasicTime = styled.img`
  width: 20px;
  height: 20px;
  object-fit: cover;
  position: absolute;
  left: 9px;
  top: 0px;
`;
