import React from "react";
import styled from "@emotion/styled";
/**
 * `<NaN>` ('메인 페이지')
 * 
 * 
 * ---
 * @example
 * ```tsx
 * import React from "react";
 * 
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <NaN/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](grida://assets-reservation/images/39:2)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 * 
 * 
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://undefined/39:2 -->
 */
export function Main() {
    return (
        <RootWrapperNaN>
        <Rectangle1/>
        <Rectangle3/>
        <Frame6>
            <Ellipse1/>
            <Ellipse2/>
            <Ellipse3/>
            <Ellipse7/>
            <Ellipse4/>
            <Ellipse5/>
            <Ellipse6/>
            <NaN_0002>
                    일              월               화              수               목              금              토
            </NaN_0002>
            <_11121314151617>
                11     12     13     14     15     16     17
            </_11121314151617>
        </Frame6>
        <Frame48>
            <NaN_0003>
            나만의 다각형
            </NaN_0003>
            <Timer/>
            <IconsBasicUser>
            <User xmlns="http://www.w3.org/2000/svg">
                <path fill="rgb(63, 67, 74)" d="M8.80577 3.36C8.80577 4.45794 7.85349 5.37 6.65 5.37C5.44652 5.37 4.49424 4.45794 4.49424 3.36C4.49424 2.26206 5.44652 1.35 6.65 1.35C7.85349 1.35 8.80577 2.26206 8.80577 3.36ZM10.2308 3.36C10.2308 5.21568 8.62761 6.72 6.65 6.72C4.6724 6.72 3.06924 5.21568 3.06924 3.36C3.06924 1.50432 4.6724 0 6.65 0C8.62761 0 10.2308 1.50432 10.2308 3.36ZM5.19025 9.03001L8.10975 9.03001C10.1355 9.03001 11.875 10.6659 11.875 12.8C11.875 12.887 11.8404 12.9536 11.7972 12.9963C11.7549 13.038 11.7135 13.05 11.678 13.05L1.62195 13.05C1.58653 13.05 1.54514 13.038 1.50285 12.9963C1.45958 12.9536 1.425 12.887 1.425 12.8C1.425 10.6659 3.16452 9.03001 5.19025 9.03001ZM0 12.8C0 9.97231 2.32375 7.68001 5.19025 7.68001L8.10975 7.68001C10.9762 7.68001 13.3 9.97231 13.3 12.8C13.3 13.6837 12.5738 14.4 11.678 14.4L1.62195 14.4C0.726172 14.4 0 13.6837 0 12.8Z"/>
            </User>
            </IconsBasicUser>
        </Frame48>
        <MyFigure>
            My figure
        </MyFigure>
        <Frame7>
            <Frame5/>
            <Group>
            <Vector xmlns="http://www.w3.org/2000/svg">
                <path fill="rgb(245, 239, 231)" d="M266 0L0 0L0 231L266 231L266 0Z"/>
            </Vector>
            <Vector_0001 xmlns="http://www.w3.org/2000/svg">
                <path fill="rgb(245, 239, 231)" d="M2.34915 106.024L38.593 205.055C44.1216 220.497 56.2848 228.381 74.9596 228.381L191.186 228.381C209.86 228.381 222.024 220.497 227.552 205.055L263.55 106.455C269.325 90.4727 264.901 77.837 250.159 68.3335L156.047 7.53259C140.567 -2.51086 125.578 -2.51086 110.098 7.53259L15.9867 68.3335C1.2434 77.837 -3.30242 90.3639 2.34915 106.024ZM21.0239 100.731C17.9524 92.5241 19.9182 87.5565 27.9041 82.2648L121.892 21.3559C130.124 16.0641 136.022 16.0641 144.13 21.3559L238.118 82.2648C246.227 87.5565 248.07 92.6319 244.998 101.056L209 199.762C205.928 207.971 201.137 210.994 191.186 210.994L74.9596 210.994C65.0079 210.994 60.2164 207.971 57.1449 199.762L21.0239 100.731Z"/>
            </Vector_0001>
            </Group>
        </Frame7>
        <Frame8>
            <Rectangle4/>
            <Rectangle6/>
            <Rectangle7/>
            <_10>
            인간관계 10%
            </_10>
            <Rectangle8/>
            <_15>
            건강 15%
            </_15>
            <_20>
            여가 20%
            </_20>
            <_30>
            학업 30%
            </_30>
        </Frame8>
        <NaN_0004>
            더보기
        </NaN_0004>
        <Frame50>
            <Frame1>
            <Group54>
                <IconsBasicProject>
                <Project xmlns="http://www.w3.org/2000/svg">
                    <path fill="rgb(63, 67, 74)" d="M8.04782 0.0752206C8.26952 -0.0250735 8.53048 -0.0250735 8.75218 0.0752206L16.3647 3.51897C16.6315 3.63966 16.8 3.88638 16.8 4.15625C16.8 4.42613 16.6315 4.67284 16.3647 4.79353L8.75218 8.23728C8.53048 8.33757 8.26952 8.33757 8.04782 8.23728L0.435319 4.79353C0.168527 4.67284 2.84818e-09 4.42613 2.84818e-09 4.15625C2.84818e-09 3.88638 0.168527 3.63966 0.435319 3.51897L8.04782 0.0752206ZM2.5484 4.15625L8.4 6.8034L14.2516 4.15625L8.4 1.5091L2.5484 4.15625ZM0.0833111 10.7253C0.277815 10.3733 0.750845 10.2306 1.13985 10.4066L8.40017 13.6911L15.6605 10.4066C16.0495 10.2306 16.5225 10.3733 16.717 10.7253C16.9115 11.0772 16.7539 11.5052 16.3649 11.6812L8.75235 15.1249C8.53065 15.2252 8.2697 15.2252 8.04799 15.1249L0.435492 11.6812C0.0464838 11.5052 -0.111193 11.0772 0.0833111 10.7253ZM1.13985 6.96288C0.750845 6.7869 0.277815 6.92956 0.0833111 7.28152C-0.111193 7.63348 0.0464838 8.06146 0.435492 8.23744L8.04799 11.6812C8.2697 11.7815 8.53065 11.7815 8.75235 11.6812L16.3649 8.23744C16.7539 8.06146 16.9115 7.63348 16.717 7.28152C16.5225 6.92956 16.0495 6.7869 15.6605 6.96288L8.40017 10.2473L1.13985 6.96288Z"/>
                </Project>
                </IconsBasicProject>
                <NaN_0005>
                나의 도형
                </NaN_0005>
            </Group54>
            <Group53>
                <IconsBasicChat>
                <Chat xmlns="http://www.w3.org/2000/svg">
                    <path fill="rgb(63, 67, 74)" d="M1.75225 1.75225C1.91376 1.59074 2.13281 1.5 2.36122 1.5L13.6398 1.5C13.8682 1.5 14.0872 1.59074 14.2488 1.75225C14.4103 1.91376 14.501 2.13281 14.501 2.36122L14.501 10.4173C14.501 10.6457 14.4103 10.8648 14.2488 11.0263C14.0872 11.1878 13.8682 11.2786 13.6398 11.2786L3.97245 11.2786C3.77353 11.2786 3.58277 11.3576 3.44212 11.4982L1.5 13.4403L1.5 2.36122C1.5 2.13281 1.59074 1.91376 1.75225 1.75225ZM2.36122 0C1.73499 0 1.1344 0.248771 0.691586 0.691586C0.248771 1.1344 0 1.73499 0 2.36122L0 15.251C0 15.5544 0.182732 15.8278 0.462987 15.9439C0.743243 16.06 1.06583 15.9958 1.28033 15.7813L4.28311 12.7786L13.6398 12.7786C14.266 12.7786 14.8666 12.5298 15.3094 12.087C15.7522 11.6442 16.001 11.0436 16.001 10.4173L16.001 2.36122C16.001 1.73499 15.7522 1.1344 15.3094 0.691586C14.8666 0.248771 14.266 0 13.6398 0L2.36122 0ZM3.74266 4C3.32845 4 2.99266 4.33579 2.99266 4.75C2.99266 5.16421 3.32845 5.5 3.74266 5.5L12.25 5.5C12.6642 5.5 13 5.16421 13 4.75C13 4.33579 12.6642 4 12.25 4L3.74266 4ZM3.75 7.00052C3.33579 7.00052 3 7.33631 3 7.75052C3 8.16474 3.33579 8.50052 3.75 8.50052L9.25311 8.50052C9.66732 8.50052 10.0031 8.16474 10.0031 7.75052C10.0031 7.33631 9.66732 7.00052 9.25311 7.00052L3.75 7.00052Z"/>
                </Chat>
                </IconsBasicChat>
                <NaN_0006>
                고민 나눔
                </NaN_0006>
            </Group53>
            <Group52>
                <IconlyRegularTwoToneHome>
                <Home>
                    <Home_0001 src="grida://assets-reservation/images/I232:751;29221:3579" alt="image of Home"/>
                </Home>
                </IconlyRegularTwoToneHome>
                <NaN_0007>
                홈
                </NaN_0007>
            </Group52>
            <Group51>
                <IconsBasicStar>
                <Star xmlns="http://www.w3.org/2000/svg">
                    <path fill="rgb(63, 67, 74)" d="M8.00002 0C8.28549 0 8.5462 0.162054 8.67255 0.418032L10.7385 4.60335L15.3585 5.27864C15.6409 5.31992 15.8754 5.51792 15.9635 5.78943C16.0515 6.06093 15.9778 6.35887 15.7733 6.55802L12.4309 9.81352L13.2197 14.4127C13.268 14.6941 13.1523 14.9785 12.9213 15.1463C12.6903 15.3141 12.3841 15.3362 12.1314 15.2033L8.00002 13.0306L3.86861 15.2033C3.61592 15.3362 3.30971 15.3141 3.07872 15.1463C2.84774 14.9785 2.73205 14.6941 2.78032 14.4127L3.56913 9.81352L0.226722 6.55802C0.0222586 6.35887 -0.0514459 6.06093 0.0365873 5.78943C0.124621 5.51792 0.359131 5.31992 0.641551 5.27864L5.26158 4.60335L7.32749 0.418032C7.45385 0.162054 7.71456 0 8.00002 0ZM8.00002 2.44444L6.4323 5.62047C6.32315 5.8416 6.11226 5.99495 5.86824 6.03061L2.36133 6.5432L4.89832 9.01423C5.07523 9.18654 5.15597 9.43489 5.11423 9.67828L4.51566 13.1683L7.65093 11.5194C7.86947 11.4045 8.13057 11.4045 8.34911 11.5194L11.4844 13.1683L10.8858 9.67828C10.8441 9.43489 10.9248 9.18654 11.1017 9.01423L13.6387 6.5432L10.1318 6.03061C9.88779 5.99495 9.6769 5.8416 9.56774 5.62047L8.00002 2.44444Z"/>
                </Star>
                </IconsBasicStar>
                <NaN_0008>
                칭찬 일기
                </NaN_0008>
            </Group51>
            <Group50>
                <NaN_0009>
                집중 기록
                </NaN_0009>
                <IconsBasicTime>
                <Time xmlns="http://www.w3.org/2000/svg">
                    <path fill="rgb(63, 67, 74)" d="M1.5 8C1.5 4.41015 4.41015 1.5 8 1.5C11.5899 1.5 14.5 4.41015 14.5 8C14.5 11.5899 11.5899 14.5 8 14.5C4.41015 14.5 1.5 11.5899 1.5 8ZM8 0C3.58172 0 0 3.58172 0 8C0 12.4183 3.58172 16 8 16C12.4183 16 16 12.4183 16 8C16 3.58172 12.4183 0 8 0ZM8.75 3.65012C8.75 3.2359 8.41421 2.90012 8 2.90012C7.58579 2.90012 7.25 3.2359 7.25 3.65012L7.25 8.00012C7.25 8.28419 7.4105 8.54389 7.66459 8.67094L10.5646 10.1209C10.9351 10.3062 11.3856 10.156 11.5708 9.78553C11.7561 9.41504 11.6059 8.96454 11.2354 8.77929L8.75 7.53659L8.75 3.65012Z"/>
                </Time>
                </IconsBasicTime>
            </Group50>
            </Frame1>
        </Frame50>
        </RootWrapperNaN>
    )
}

const RootWrapperNaN = styled.div`
	min-height: 100vh;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: relative;
`;

const Rectangle1 = styled.div`
	width: 1px;
	height: 1px;
	background: rgb(217, 217, 217);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Rectangle3 = styled.div`
	width: 1px;
	height: 3px;
	background: rgb(217, 217, 217);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: absolute;
	left: 360px;
	top: 37px;
`;

const Frame6 = styled.div`
	width: 360px;
	height: 102px;
	overflow: hidden;
	border: solid 1px rgb(217, 217, 217);
	position: absolute;
	left: 0px;
	top: 72px;
`;

const Ellipse1 = styled.div`
	width: 38px;
	height: 38px;
	background: rgb(33, 53, 85);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 38px / 38px;
	position: absolute;
	left: 13px;
	top: 32px;
`;

const Ellipse2 = styled.div`
	width: 38px;
	height: 38px;
	background: rgb(33, 53, 85);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 38px / 38px;
	position: absolute;
	left: 61px;
	top: 32px;
`;

const Ellipse3 = styled.div`
	width: 38px;
	height: 38px;
	background: rgb(33, 53, 85);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 38px / 38px;
	position: absolute;
	left: 111px;
	top: 32px;
`;

const Ellipse7 = styled.div`
	width: 38px;
	height: 38px;
	background: rgb(33, 53, 85);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 38px / 38px;
	position: absolute;
	left: 161px;
	top: 32px;
`;

const Ellipse4 = styled.div`
	width: 38px;
	height: 38px;
	background: rgb(33, 53, 85);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 38px / 38px;
	position: absolute;
	left: 211px;
	top: 32px;
`;

const Ellipse5 = styled.div`
	width: 38px;
	height: 38px;
	box-shadow: 0px 4px 4px  rgba(0, 0, 0, 0.25);
	background: rgb(33, 53, 85);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 38px / 38px;
	position: absolute;
	left: 260px;
	top: 32px;
`;

const Ellipse6 = styled.div`
	width: 38px;
	height: 38px;
	background: rgb(33, 53, 85);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 38px / 38px;
	position: absolute;
	left: 310px;
	top: 32px;
`;

const NaN_0002 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Inter, sans-serif;
	font-weight: initial;
	text-align: left;
	width: 360px;
	min-height: 16px;
	position: absolute;
	left: 0px;
	top: 75px;
	height: 16px;
`;

const _11121314151617 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Inter, sans-serif;
	font-weight: initial;
	text-align: left;
	width: 342px;
	min-height: 23px;
	position: absolute;
	left: 11px;
	top: 39px;
	height: 23px;
`;

const Frame48 = styled.div`
	width: 360px;
	height: 54px;
	overflow: hidden;
	background: rgb(245, 239, 231);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const NaN_0003 = styled.span`
	color: rgba(0, 0, 0, 0.7);
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Inter, sans-serif;
	font-weight: initial;
	text-align: center;
	text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
	width: 147px;
	min-height: 28px;
	position: absolute;
	left: 108px;
	top: 14px;
	height: 28px;
`;

const Timer = styled.div`
	width: 19px;
	height: 18px;
	overflow: hidden;
	position: absolute;
	left: calc((calc((50% + 112px)) - 10px));
	top: calc((calc((50% + 0px)) - 9px));
`;

const IconsBasicUser = styled.div`
	width: 19px;
	height: 18px;
	position: absolute;
	left: 323px;
	top: 19px;
`;

const User = styled.svg`
	width: 13px;
	height: 14px;
	position: absolute;
	left: 1px;
	top: 2px;
	right: 5px;
	bottom: 2px;
`;

const MyFigure = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 15px;
	font-family: Inter, sans-serif;
	font-weight: initial;
	text-align: left;
	text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
	width: 95px;
	min-height: 17px;
	position: absolute;
	left: 34px;
	top: 208px;
	height: 17px;
`;

const Frame7 = styled.div`
	width: 330px;
	height: 330px;
	overflow: hidden;
	position: absolute;
	box-shadow: 0px 4px 4px  rgba(0, 0, 0, 0.25);
	left: 17px;
	top: 222px;
`;

const Frame5 = styled.div`
	width: 310px;
	height: 308px;
	overflow: hidden;
	background: rgb(79, 112, 156);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 10px;
	position: absolute;
	box-shadow: 0px 4px 4px  rgba(0, 0, 0, 0.25);
	left: 8px;
	top: 12px;
`;

const Group = styled.div`
	width: 266px;
	height: 231px;
	position: absolute;
	box-shadow: 0px 4px 4px  rgba(0, 0, 0, 0.25);
	left: 30px;
	top: 38px;
`;

const Vector = styled.svg`
	width: 266px;
	height: 231px;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
	opacity: 0;
`;

const Vector_0001 = styled.svg`
	width: 266px;
	height: 228px;
	position: absolute;
	left: -0px;
	top: 3px;
	right: 0px;
	bottom: 0px;
`;

const Frame8 = styled.div`
	width: 320px;
	height: 129px;
	overflow: hidden;
	position: absolute;
	left: 20px;
	top: 586px;
`;

const Rectangle4 = styled.div`
	width: 149px;
	height: 46px;
	box-shadow: 0px 4px 4px  rgba(0, 0, 0, 0.25);
	background: rgb(33, 53, 85), rgb(33, 53, 85), rgb(33, 53, 85);
	background-repeat: no-repeat, no-repeat, no-repeat;
	background-size: contain, contain, contain;
	background-position: center, center, center;
	border-radius: 10px;
	position: absolute;
	left: 5px;
	top: 4px;
`;

const Rectangle6 = styled.div`
	width: 149px;
	height: 46px;
	box-shadow: 0px 4px 4px  rgba(0, 0, 0, 0.25);
	background: rgb(33, 53, 85), rgb(33, 53, 85), rgb(33, 53, 85);
	background-repeat: no-repeat, no-repeat, no-repeat;
	background-size: contain, contain, contain;
	background-position: center, center, center;
	border-radius: 10px;
	position: absolute;
	left: 166px;
	top: 4px;
`;

const Rectangle7 = styled.div`
	width: 149px;
	height: 46px;
	box-shadow: 0px 4px 4px  rgba(0, 0, 0, 0.25);
	background: rgb(33, 53, 85), rgb(33, 53, 85), rgb(33, 53, 85);
	background-repeat: no-repeat, no-repeat, no-repeat;
	background-size: contain, contain, contain;
	background-position: center, center, center;
	border-radius: 10px;
	position: absolute;
	left: 5px;
	top: 62px;
`;

const _10 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: initial;
	text-align: left;
	width: 137px;
	min-height: 23px;
	position: absolute;
	left: 9px;
	top: 73px;
	height: 23px;
`;

const Rectangle8 = styled.div`
	width: 149px;
	height: 46px;
	box-shadow: 0px 4px 4px  rgba(0, 0, 0, 0.25);
	background: rgb(33, 53, 85), rgb(33, 53, 85), rgb(33, 53, 85);
	background-repeat: no-repeat, no-repeat, no-repeat;
	background-size: contain, contain, contain;
	background-position: center, center, center;
	border-radius: 10px;
	position: absolute;
	left: 166px;
	top: 62px;
`;

const _15 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: initial;
	text-align: left;
	width: 136px;
	min-height: 23px;
	position: absolute;
	left: 12px;
	top: 15px;
	height: 23px;
`;

const _20 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: initial;
	text-align: left;
	width: 136px;
	min-height: 23px;
	position: absolute;
	left: 173px;
	top: 15px;
	height: 23px;
`;

const _30 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: initial;
	text-align: left;
	width: 136px;
	min-height: 23px;
	position: absolute;
	left: 173px;
	top: 73px;
	height: 23px;
`;

const NaN_0004 = styled.span`
	color: rgba(0, 0, 0, 0.79);
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Inter, sans-serif;
	font-weight: initial;
	text-align: left;
	width: 38px;
	min-height: 14px;
	position: absolute;
	left: 300px;
	top: 572px;
	height: 14px;
`;

const Frame50 = styled.div`
	width: 360px;
	height: 52px;
	overflow: hidden;
	background: rgb(245, 239, 231);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: absolute;
	left: 0px;
	top: 748px;
`;

const Frame1 = styled.div`
	width: 360px;
	height: 52px;
	overflow: hidden;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Group54 = styled.div`
	width: 41px;
	height: 30px;
	position: absolute;
	left: 297px;
	top: 16px;
`;

const IconsBasicProject = styled.div`
	position: absolute;
	left: 10px;
	top: 0px;
	right: 10px;
	bottom: 11px;
`;

const Project = styled.svg`
	width: 17px;
	height: 15px;
	position: absolute;
	left: 1px;
	top: 2px;
	right: 3px;
	bottom: 2px;
`;

const NaN_0005 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 8px;
	font-family: Inter, sans-serif;
	font-weight: initial;
	text-align: center;
	width: 42px;
	position: absolute;
	left: 0px;
	top: 20px;
`;

const Group53 = styled.div`
	width: 36px;
	height: 32px;
	position: absolute;
	left: 233px;
	top: 14px;
`;

const IconsBasicChat = styled.div`
	width: 20px;
	height: 20px;
	position: absolute;
	left: 8px;
	top: 0px;
`;

const Chat = styled.svg`
	width: 16px;
	height: 16px;
	position: absolute;
	left: 2px;
	top: 4px;
	right: 2px;
	bottom: -0px;
`;

const NaN_0006 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 8px;
	font-family: Inter, sans-serif;
	font-weight: initial;
	text-align: center;
	width: 37px;
	position: absolute;
	left: 0px;
	top: 22px;
`;

const Group52 = styled.div`
	width: 20px;
	height: 28px;
	position: absolute;
	left: 170px;
	top: 18px;
`;

const IconlyRegularTwoToneHome = styled.div`
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 11px;
`;

const Home = styled.div`
	width: 16px;
	height: 14px;
	position: absolute;
	left: 2px;
	top: 1px;
`;

const Home_0001 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
`;

const NaN_0007 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 8px;
	font-family: Inter, sans-serif;
	font-weight: initial;
	text-align: center;
	width: 14px;
	position: absolute;
	left: 3px;
	top: 18px;
`;

const Group51 = styled.div`
	width: 36px;
	height: 30px;
	position: absolute;
	left: 92px;
	top: 16px;
`;

const IconsBasicStar = styled.div`
	width: 20px;
	height: 20px;
	position: absolute;
	left: 8px;
	top: 0px;
`;

const Star = styled.svg`
	width: 16px;
	height: 15px;
	position: absolute;
	left: 2px;
	top: 2px;
	right: 2px;
	bottom: 2px;
`;

const NaN_0008 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 8px;
	font-family: Inter, sans-serif;
	font-weight: initial;
	text-align: center;
	width: 37px;
	position: absolute;
	left: 0px;
	top: 20px;
`;

const Group50 = styled.div`
	width: 37px;
	height: 30px;
	position: absolute;
	left: 21px;
	top: 16px;
`;

const NaN_0009 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 8px;
	font-family: Inter, sans-serif;
	font-weight: initial;
	text-align: center;
	width: 38px;
	position: absolute;
	left: 0px;
	top: 20px;
`;

const IconsBasicTime = styled.div`
	width: 20px;
	height: 20px;
	position: absolute;
	left: 9px;
	top: 0px;
`;

const Time = styled.svg`
	width: 16px;
	height: 16px;
	position: absolute;
	left: 2px;
	top: 2px;
	right: 2px;
	bottom: 2px;
`;