import React from "react";
import * as F from "./FirstPageStyle";

/**
 * 
 * `<NaN>` ('시작 페이지')
 * 
 * 
 * ---
 * @example
 * ```tsx
 * import React from "react";
 * 
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <NaN/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](grida://assets-reservation/images/129:588)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 * 
 * 
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://undefined/129:588 -->
 */

export function FirstPage() {
  return (
    <F.RootWrapperNaN>
      <F.Rectangle3/>
      <F.Rectangle37/>
      <F.Rectangle38/>
      <F.Typography>
        <F.Typography_0001>
          안녕하세요!<br/>
      나만의 도형을 만들어가는 서비스 <br/>
      ‘나만의 다각형’입니다
        </F.Typography_0001>
      </F.Typography>
      <F.Typography_0002>
        <F.Typography_0001>
          
        </F.Typography_0001>
      </F.Typography_0002>
      <F.Group12>
        <F.Rectangle23/>
        <F.NaN_0002>
          회원가입
        </F.NaN_0002>
      </F.Group12>
      <F.Group12_0001>
        <F.Rectangle25/>
        <F.NaN_0003>
          로그인
        </F.NaN_0003>
      </F.Group12_0001>
        <F.LogoImg src="/logo.png" alt="로고 이미지" />
      <F.Line16/>
      <F.Line17/>
    </F.RootWrapperNaN>
  )
}

